#!/usr/bin/env python3
"""
Simple PDF generator for Backend Manager documentation
Uses markdown2 and HTML output for browser-based PDF conversion
"""

import os
from datetime import datetime
from pathlib import Path

try:
    import markdown2
except ImportError:
    print("Installing markdown2...")
    os.system("pip3 install markdown2")
    import markdown2

PROJECT_ROOT = Path(__file__).parent
DOCS_DIR = PROJECT_ROOT / "docs"
HTML_OUTPUT_DIR = PROJECT_ROOT / "pdf_html"

# Create output directory
HTML_OUTPUT_DIR.mkdir(exist_ok=True)

# CSS for HTML that can be printed to PDF
PDF_CSS = """
<style>
@media print {
    @page {
        size: A4;
        margin: 2cm;
    }
    
    h1, h2, h3 {
        page-break-after: avoid;
    }
    
    pre, table {
        page-break-inside: avoid;
    }
}

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
    line-height: 1.6;
    color: #333;
    max-width: 900px;
    margin: 0 auto;
    padding: 20px;
}

h1 {
    color: #2c3e50;
    border-bottom: 3px solid #3498db;
    padding-bottom: 10px;
    margin-top: 30px;
}

h2 {
    color: #34495e;
    border-bottom: 2px solid #95a5a6;
    padding-bottom: 5px;
    margin-top: 25px;
}

h3 {
    color: #555;
    margin-top: 20px;
}

code {
    background-color: #f4f4f4;
    padding: 2px 6px;
    border-radius: 3px;
    font-family: 'Monaco', 'Courier New', monospace;
    font-size: 0.9em;
}

pre {
    background-color: #f8f8f8;
    border: 1px solid #ddd;
    border-radius: 5px;
    padding: 15px;
    overflow-x: auto;
}

pre code {
    background-color: transparent;
    padding: 0;
}

table {
    border-collapse: collapse;
    width: 100%;
    margin: 20px 0;
}

table th {
    background-color: #3498db;
    color: white;
    padding: 12px;
    text-align: left;
    font-weight: bold;
}

table td {
    border: 1px solid #ddd;
    padding: 10px;
}

table tr:nth-child(even) {
    background-color: #f9f9f9;
}

blockquote {
    border-left: 4px solid #3498db;
    padding-left: 20px;
    margin: 20px 0;
    color: #555;
    font-style: italic;
}

ul, ol {
    margin: 15px 0;
    padding-left: 30px;
}

li {
    margin: 8px 0;
}

a {
    color: #3498db;
    text-decoration: none;
}

.header {
    text-align: center;
    margin-bottom: 40px;
    padding-bottom: 20px;
    border-bottom: 3px solid #3498db;
}

.header h1 {
    color: #2c3e50;
    margin: 10px 0;
    border: none;
}

.header p {
    color: #7f8c8d;
    font-size: 0.9em;
}

.print-button {
    position: fixed;
    top: 20px;
    right: 20px;
    padding: 10px 20px;
    background: #3498db;
    color: white;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    font-size: 14px;
    box-shadow: 0 2px 5px rgba(0,0,0,0.2);
}

.print-button:hover {
    background: #2980b9;
}

@media print {
    .print-button {
        display: none;
    }
}
</style>
"""


def create_html_header(title: str) -> str:
    """Create HTML header"""
    return f"""
    <div class="header">
        <h1>🤖 V-Mart Personal AI Agent</h1>
        <h1>{title}</h1>
        <p>Generated: {datetime.now().strftime("%B %d, %Y")}</p>
        <p><a href="https://github.com/ds25041974/V-Mart-Personal-AI-Agent">GitHub Repository</a></p>
    </div>
    """


def convert_md_to_html(md_file: Path) -> bool:
    """Convert markdown to HTML for PDF printing"""
    try:
        # Read markdown
        with open(md_file, "r", encoding="utf-8") as f:
            md_content = f.read()

        # Convert to HTML
        html_content = markdown2.markdown(
            md_content,
            extras=[
                "fenced-code-blocks",
                "tables",
                "header-ids",
                "toc",
                "code-friendly",
                "strike",
                "task_list",
            ],
        )

        # Create title
        title = md_file.stem.replace("_", " ").replace("-", " ").title()

        # Create full HTML
        full_html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{title} - V-Mart AI Agent</title>
    {PDF_CSS}
    <script>
        function printToPDF() {{
            window.print();
        }}
    </script>
</head>
<body>
    <button class="print-button" onclick="printToPDF()">🖨️ Print to PDF</button>
    {create_html_header(title)}
    {html_content}
    <hr>
    <p style="text-align: center; color: #999; font-size: 0.9em;">
        Generated by V-Mart Personal AI Agent Documentation System<br>
        © 2025 All Rights Reserved
    </p>
</body>
</html>
"""

        # Save HTML
        html_file = HTML_OUTPUT_DIR / f"{md_file.stem}.html"
        with open(html_file, "w", encoding="utf-8") as f:
            f.write(full_html)

        size_kb = html_file.stat().st_size / 1024
        print(f"✓ {md_file.name:45s} → {html_file.name:45s} ({size_kb:.1f} KB)")
        return True

    except Exception as e:
        print(f"✗ {md_file.name:45s} → Error: {str(e)}")
        return False


def main():
    """Main function"""
    print("╔══════════════════════════════════════════════════════════════════╗")
    print("║   Backend Manager Documentation - HTML Generator for PDF        ║")
    print("╚══════════════════════════════════════════════════════════════════╝")
    print()

    # Convert BACKEND_MANAGER.md
    backend_doc = DOCS_DIR / "BACKEND_MANAGER.md"

    if not backend_doc.exists():
        print(f"❌ Error: {backend_doc} not found!")
        return

    print(f"📁 Output directory: {HTML_OUTPUT_DIR}")
    print()
    print("Converting documentation:")
    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")

    success = convert_md_to_html(backend_doc)

    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    print()

    if success:
        html_file = HTML_OUTPUT_DIR / "BACKEND_MANAGER.html"
        print("✅ HTML file created successfully!")
        print()
        print("📄 To create PDF:")
        print(f"   1. Open: {html_file}")
        print("   2. Click 'Print to PDF' button or use Cmd+P (Mac) / Ctrl+P (Windows)")
        print("   3. Select 'Save as PDF' from print dialog")
        print("   4. Save to: pdf/docs/BACKEND_MANAGER.pdf")
        print()
        print(f"🌐 Or open in browser: file://{html_file.absolute()}")
        print()

        # Try to open in browser
        try:
            import webbrowser

            webbrowser.open(f"file://{html_file.absolute()}")
            print("🚀 Opening in your default browser...")
        except Exception:
            pass
    else:
        print("❌ Conversion failed!")

    print()


if __name__ == "__main__":
    main()
